name: Build BusyBox minimal

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Clone BusyBox
        run: |
          git clone https://git.busybox.net/busybox
          cd busybox
          make defconfig

      - name: Create minimal config
        run: |
          cd busybox

          printf '%s\n' \
"CONFIG_STATIC=y" \
"CONFIG_CAT=y" \
"CONFIG_LS=y" \
"CONFIG_ECHO=y" \
"CONFIG_GREP=y" \
"CONFIG_PWD=y" \
"CONFIG_MKDIR=y" \
"CONFIG_RM=y" \
"CONFIG_TOUCH=y" \
"CONFIG_CP=y" \
"CONFIG_MV=y" \
"CONFIG_FIND=y" \
"CONFIG_FEATURE_UTMP=n" \
"CONFIG_FEATURE_WTMP=n" \
"CONFIG_FEATURE_SUID=n" \
"CONFIG_PAM=n" \
"CONFIG_DESKTOP=n" \
"CONFIG_EXTRA_COMPAT=n" \
> .config

      - name: Build config (non-interactive)
        run: |
          cd busybox
          yes "" | make oldconfig || true

      - name: Build BusyBox
        run: |
          cd busybox
          make -j$(sysctl -n hw.ncpu)

      - name: Output check
        run: |
          cd busybox
          ls -la busybox
